"""Canonical era mapping for targeted narrative requests.

Generated from the archive database (wiki_pages, kim_dialogues,
game_dialogues, warframes, game_quests).  Keys are lowercase substrings;
values are free-form era labels injected into the targeted-story directive.
"""

from __future__ import annotations

# Targeted subjects with a canonical era.  When a story request names one
# of them, the bot skips the lens menu and anchors the answer in that era.
TARGETED_SUBJECT_ERAS: dict[str, str] = {
    # 1999 (Höllvania)
    "1999": "1999 (Höllvania)",
    "amir": "1999 (Höllvania)",
    "aoi": "1999 (Höllvania)",
    "arthur": "1999 (Höllvania)",
    "atomicycle": "1999 (Höllvania)",
    "eleanor": "1999 (Höllvania)",
    "fables & frontiers": "1999 (Höllvania)",
    "fables and frontiers": "1999 (Höllvania)",
    "flare": "1999 (Höllvania)",
    "hex": "1999 (Höllvania)",
    "hollvania": "1999 (Höllvania)",
    "höllvania": "1999 (Höllvania)",
    "kaya": "1999 (Höllvania)",
    "leticia": "1999 (Höllvania)",
    "lettie": "1999 (Höllvania)",
    "lizzie": "1999 (Höllvania)",
    "loid": "1999 (Höllvania)",
    "lyon": "1999 (Höllvania)",
    "marie": "1999 (Höllvania)",
    "minerva": "1999 (Höllvania)",
    "ollie": "1999 (Höllvania)",
    "quincy": "1999 (Höllvania)",
    "roathe": "1999 (Höllvania)",
    "scaldra": "1999 (Höllvania)",
    "technocyte": "1999 (Höllvania)",
    "techrot": "1999 (Höllvania)",
    "the hex": "1999 (Höllvania)",
    "velimir": "1999 (Höllvania)",
    "viktor": "1999 (Höllvania)",
    "zeke": "1999 (Höllvania)",
    # l'Ère Corpus
    "alad v": "l'Ère Corpus",
    "corpus": "l'Ère Corpus",
    "deadlock protocol": "l'Ère Corpus",
    "frohd bek": "l'Ère Corpus",
    "nef anyo": "l'Ère Corpus",
    "parvos": "l'Ère Corpus",
    "parvos granum": "l'Ère Corpus",
    "sisters of parvos": "l'Ère Corpus",
    "vala glarios": "l'Ère Corpus",
    # l'Ère Grineer
    "grineer": "l'Ère Grineer",
    "grineer queens": "l'Ère Grineer",
    "kuva": "l'Ère Grineer",
    "kuva lich": "l'Ère Grineer",
    "leekter": "l'Ère Grineer",
    "shik tal": "l'Ère Grineer",
    "the grustrag three": "l'Ère Grineer",
    "vem tabook": "l'Ère Grineer",
    "wolf of saturn six": "l'Ère Grineer",
    # l'Ère Orokin
    "albrecht": "l'Ère Orokin",
    "albrecht entrati": "l'Ère Orokin",
    "cephalon": "l'Ère Orokin",
    "cephalon acetuma": "l'Ère Orokin",
    "chimera prologue": "l'Ère Orokin",
    "dominus thrax": "l'Ère Orokin",
    "duviri": "l'Ère Orokin",
    "entrati": "l'Ère Orokin",
    "erra": "l'Ère Orokin",
    "executor": "l'Ère Orokin",
    "executor avantus": "l'Ère Orokin",
    "executor karishh": "l'Ère Orokin",
    "executor nitokh": "l'Ère Orokin",
    "executor scarne": "l'Ère Orokin",
    "executor tormis": "l'Ère Orokin",
    "executor tuvul": "l'Ère Orokin",
    "heart of deimos": "l'Ère Orokin",
    "indifference": "l'Ère Orokin",
    "indifférence": "l'Ère Orokin",
    "man in the wall": "l'Ère Orokin",
    "orokin": "l'Ère Orokin",
    "the duviri paradox": "l'Ère Orokin",
    "the maker": "l'Ère Orokin",
    "the man in the wall": "l'Ère Orokin",
    "tower of the unum": "l'Ère Orokin",
    "unum": "l'Ère Orokin",
    "void": "l'Ère Orokin",
    "whispers in the walls": "l'Ère Orokin",
    # l'Éveil du Tenno
    "angels of the zariman": "l'Éveil du Tenno",
    "apostasy prologue": "l'Éveil du Tenno",
    "archimedean yonta": "l'Éveil du Tenno",
    "ash": "l'Éveil du Tenno",
    "atlas": "l'Éveil du Tenno",
    "awakening": "l'Éveil du Tenno",
    "ballas": "l'Éveil du Tenno",
    "banshee": "l'Éveil du Tenno",
    "baruuk": "l'Éveil du Tenno",
    "business": "l'Éveil du Tenno",
    "caliban": "l'Éveil du Tenno",
    "captain vor": "l'Éveil du Tenno",
    "cavalero": "l'Éveil du Tenno",
    "cephalon cordylon": "l'Éveil du Tenno",
    "cephalon cy": "l'Éveil du Tenno",
    "cephalon melica": "l'Éveil du Tenno",
    "cephalon simaris": "l'Éveil du Tenno",
    "cephalon suda": "l'Éveil du Tenno",
    "cephalon vull": "l'Éveil du Tenno",
    "chroma": "l'Éveil du Tenno",
    "citrine": "l'Éveil du Tenno",
    "cordylon": "l'Éveil du Tenno",
    "councilor vay hek": "l'Éveil du Tenno",
    "cy": "l'Éveil du Tenno",
    "cyte-09": "l'Éveil du Tenno",
    "dagath": "l'Éveil du Tenno",
    "dante": "l'Éveil du Tenno",
    "darvo": "l'Éveil du Tenno",
    "daughter": "l'Éveil du Tenno",
    "drifter": "l'Éveil du Tenno",
    "ember": "l'Éveil du Tenno",
    "equinox": "l'Éveil du Tenno",
    "eudico": "l'Éveil du Tenno",
    "excalibur": "l'Éveil du Tenno",
    "father": "l'Éveil du Tenno",
    "fisher hai-luk": "l'Éveil du Tenno",
    "follie": "l'Éveil du Tenno",
    "frost": "l'Éveil du Tenno",
    "gara": "l'Éveil du Tenno",
    "gauss": "l'Éveil du Tenno",
    "general sargas ruk": "l'Éveil du Tenno",
    "grandmother": "l'Éveil du Tenno",
    "grendel": "l'Éveil du Tenno",
    "gyre": "l'Éveil du Tenno",
    "harrow": "l'Éveil du Tenno",
    "hildryn": "l'Éveil du Tenno",
    "hok": "l'Éveil du Tenno",
    "hydroid": "l'Éveil du Tenno",
    "inaros": "l'Éveil du Tenno",
    "ivara": "l'Éveil du Tenno",
    "jade": "l'Éveil du Tenno",
    "jade shadows": "l'Éveil du Tenno",
    "jade shadows: constellations": "l'Éveil du Tenno",
    "kahl": "l'Éveil du Tenno",
    "kahl-175": "l'Éveil du Tenno",
    "kela de thaym": "l'Éveil du Tenno",
    "khora": "l'Éveil du Tenno",
    "konzu": "l'Éveil du Tenno",
    "koumei": "l'Éveil du Tenno",
    "kullervo": "l'Éveil du Tenno",
    "lavos": "l'Éveil du Tenno",
    "lech kril": "l'Éveil du Tenno",
    "lieutenant lech kril": "l'Éveil du Tenno",
    "limbo": "l'Éveil du Tenno",
    "little duck": "l'Éveil du Tenno",
    "loki": "l'Éveil du Tenno",
    "lotus": "l'Éveil du Tenno",
    "mag": "l'Éveil du Tenno",
    "margulis": "l'Éveil du Tenno",
    "maroo": "l'Éveil du Tenno",
    "master teasonai": "l'Éveil du Tenno",
    "melica": "l'Éveil du Tenno",
    "mesa": "l'Éveil du Tenno",
    "mirage": "l'Éveil du Tenno",
    "mother": "l'Éveil du Tenno",
    "nakak": "l'Éveil du Tenno",
    "natah": "l'Éveil du Tenno",
    "nekros": "l'Éveil du Tenno",
    "nezha": "l'Éveil du Tenno",
    "nidus": "l'Éveil du Tenno",
    "nokko": "l'Éveil du Tenno",
    "nora night": "l'Éveil du Tenno",
    "nova": "l'Éveil du Tenno",
    "nyx": "l'Éveil du Tenno",
    "oberon": "l'Éveil du Tenno",
    "octavia": "l'Éveil du Tenno",
    "old man suumbaat": "l'Éveil du Tenno",
    "once awake": "l'Éveil du Tenno",
    "onkk": "l'Éveil du Tenno",
    "operator": "l'Éveil du Tenno",
    "opérateur": "l'Éveil du Tenno",
    "oraxia": "l'Éveil du Tenno",
    "ordis": "l'Éveil du Tenno",
    "orion & sirius": "l'Éveil du Tenno",
    "ostron": "l'Éveil du Tenno",
    "otak": "l'Éveil du Tenno",
    "palladino": "l'Éveil du Tenno",
    "protea": "l'Éveil du Tenno",
    "qorvex": "l'Éveil du Tenno",
    "quinn": "l'Éveil du Tenno",
    "revenant": "l'Éveil du Tenno",
    "rhino": "l'Éveil du Tenno",
    "rising tide": "l'Éveil du Tenno",
    "rok": "l'Éveil du Tenno",
    "sargas ruk": "l'Éveil du Tenno",
    "saryn": "l'Éveil du Tenno",
    "saya": "l'Éveil du Tenno",
    "sevagoth": "l'Éveil du Tenno",
    "simaris": "l'Éveil du Tenno",
    "sirius & orion": "l'Éveil du Tenno",
    "smokefinger": "l'Éveil du Tenno",
    "solaris united": "l'Éveil du Tenno",
    "son": "l'Éveil du Tenno",
    "styanax": "l'Éveil du Tenno",
    "suda": "l'Éveil du Tenno",
    "temple": "l'Éveil du Tenno",
    "tenno": "l'Éveil du Tenno",
    "teshin": "l'Éveil du Tenno",
    "the archwing": "l'Éveil du Tenno",
    "the businessman": "l'Éveil du Tenno",
    "the lotus eaters": "l'Éveil du Tenno",
    "the new war": "l'Éveil du Tenno",
    "the sacrifice": "l'Éveil du Tenno",
    "the second dream": "l'Éveil du Tenno",
    "the sergeant": "l'Éveil du Tenno",
    "the war within": "l'Éveil du Tenno",
    "titania": "l'Éveil du Tenno",
    "trinity": "l'Éveil du Tenno",
    "tyl regor": "l'Éveil du Tenno",
    "uriel": "l'Éveil du Tenno",
    "valkyr": "l'Éveil du Tenno",
    "vauban": "l'Éveil du Tenno",
    "vay hek": "l'Éveil du Tenno",
    "ventkids": "l'Éveil du Tenno",
    "veso": "l'Éveil du Tenno",
    "volt": "l'Éveil du Tenno",
    "vor": "l'Éveil du Tenno",
    "vor's prize": "l'Éveil du Tenno",
    "voruna": "l'Éveil du Tenno",
    "voyageur": "l'Éveil du Tenno",
    "vull": "l'Éveil du Tenno",
    "warframe": "l'Éveil du Tenno",
    "wisp": "l'Éveil du Tenno",
    "wukong": "l'Éveil du Tenno",
    "xaku": "l'Éveil du Tenno",
    "yareli": "l'Éveil du Tenno",
    "yonta": "l'Éveil du Tenno",
    "zariman": "l'Éveil du Tenno",
    "zephyr": "l'Éveil du Tenno",
    # la Vieille Guerre
    "archon": "la Vieille Guerre",
    "archon amar": "la Vieille Guerre",
    "archon boreal": "la Vieille Guerre",
    "archon nira": "la Vieille Guerre",
    "hunhow": "la Vieille Guerre",
    "old war": "la Vieille Guerre",
    "sentient": "la Vieille Guerre",
    "the old peace": "la Vieille Guerre",
    "vieille guerre": "la Vieille Guerre",
}

# Warframes whose canonical story is told by Drusus in the Leverian.
# When a story request names one of them, the answer must be anchored on
# Drusus' narration in the Leverian gallery.
LEVERIAN_WARFRAMES: frozenset[str] = frozenset((
    "ash",
    "atlas",
    "dante",
    "gauss",
    "grendel",
    "ivara",
    "lavos",
    "nezha",
    "nova",
    "styanax",
    "voruna",
))
